# https://docs.github.com/ja/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      opentelemetry:
        patterns:
          - go.opentelemetry.io/*

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "daily"
