// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     v1.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/container"
	"github.com/actgardner/gogen-avro/v10/vm"
)

func NewAccessLogWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewAccessLog()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type AccessLogReader struct {
	r io.Reader
	p *vm.Program
}

func NewAccessLogReader(r io.Reader) (*AccessLogReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewAccessLog()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &AccessLogReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r AccessLogReader) Read() (AccessLog, error) {
	t := NewAccessLog()
	err := vm.Eval(r.r, r.p, &t)
	return t, err
}
