// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/ww24/linebot/config"
	"github.com/ww24/linebot/domain/service"
	"github.com/ww24/linebot/infra/external/linebot"
	"github.com/ww24/linebot/infra/firestore"
	"github.com/ww24/linebot/infra/scheduler"
	"github.com/ww24/linebot/interactor"
	"github.com/ww24/linebot/nl"
	"github.com/ww24/linebot/presentation/http"
)

// Injectors from wire.go:

func register(contextContext context.Context) (*bot, error) {
	configConfig := config.NewConfig()
	logger, err := newLogger(contextContext)
	if err != nil {
		return nil, err
	}
	lineBot, err := linebot.NewLINEBot(configConfig)
	if err != nil {
		return nil, err
	}
	messageProviderSet := linebot.NewMessageProviderSet()
	botImpl := service.NewBot(lineBot, messageProviderSet)
	client, err := firestore.New(contextContext)
	if err != nil {
		return nil, err
	}
	conversation := firestore.NewConversation(client)
	conversationImpl := service.NewConversation(conversation)
	shoppingImpl := service.NewShopping(conversation)
	parser, err := nl.NewParser()
	if err != nil {
		return nil, err
	}
	shopping := interactor.NewShopping(conversationImpl, shoppingImpl, parser, messageProviderSet, botImpl)
	reminder := firestore.NewReminder(conversation)
	schedulerScheduler, err := scheduler.New(contextContext, configConfig)
	if err != nil {
		return nil, err
	}
	reminderImpl := service.NewReminder(reminder, schedulerScheduler)
	interactorReminder := interactor.NewReminder(conversationImpl, reminderImpl, messageProviderSet, botImpl)
	eventHandler, err := interactor.NewEventHandler(shopping, interactorReminder, reminderImpl, messageProviderSet, botImpl, configConfig)
	if err != nil {
		return nil, err
	}
	handler := http.NewHandler(logger, botImpl, eventHandler)
	mainBot := newBot(configConfig, handler)
	return mainBot, nil
}
