// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/ww24/linebot/bot"
	"github.com/ww24/linebot/domain/service"
	"github.com/ww24/linebot/infra/firestore"
)

// Injectors from wire.go:

func register(contextContext context.Context, config bot.Config) (*bot.Bot, error) {
	logger, err := newLogger()
	if err != nil {
		return nil, err
	}
	client, err := firestore.New(contextContext)
	if err != nil {
		return nil, err
	}
	conversation := firestore.NewConversation(client)
	shoppingImpl, err := service.NewShopping(conversation)
	if err != nil {
		return nil, err
	}
	shoppingService, err := bot.NewShoppingService(shoppingImpl)
	if err != nil {
		return nil, err
	}
	botBot, err := bot.New(config, logger, shoppingService)
	if err != nil {
		return nil, err
	}
	return botBot, nil
}
