// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/ww24/linebot/config"
	"github.com/ww24/linebot/infra/browser"
	"github.com/ww24/linebot/interactor"
	"github.com/ww24/linebot/presentation/http"
)

// Injectors from wire.go:

func register(ctx context.Context) (*server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	logger, err := newLogger(ctx)
	if err != nil {
		return nil, err
	}
	browserBrowser := browser.NewBrowser(configConfig)
	screenshot := interactor.NewScreenshot(browserBrowser)
	screenshotHandler := http.NewScreenshotHandler(logger, screenshot)
	mainServer := newServer(configConfig, screenshotHandler)
	return mainServer, nil
}
