// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/ww24/linebot/config"
	"github.com/ww24/linebot/infra/browser"
	"github.com/ww24/linebot/interactor"
	"github.com/ww24/linebot/presentation/http"
	"github.com/ww24/linebot/tracer"
)

// Injectors from wire.go:

func register(ctx context.Context) (*server, func(), error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	logger, err := newLogger(ctx)
	if err != nil {
		return nil, nil, err
	}
	browserBrowser := browser.NewBrowser(configConfig)
	screenshot := interactor.NewScreenshot(browserBrowser)
	screenshotHandler := http.NewScreenshotHandler(logger, screenshot)
	tracerConfig := _wireConfigValue
	spanExporter := tracer.NewCloudTraceExporter()
	tracerProvider, cleanup := tracer.New(tracerConfig, configConfig, spanExporter)
	mainServer := newServer(configConfig, screenshotHandler, tracerProvider)
	return mainServer, func() {
		cleanup()
	}, nil
}

var (
	_wireConfigValue = tc
)
