name: commitlint
on: [pull_request]

jobs:
  commitlint:
    name: Commitlint
    runs-on: ubuntu-22.04
    permissions:
      contents: "read"
      pull-requests: "read"
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - uses: wagoid/commitlint-github-action@v5.4.1
