name: commitlint
on: [pull_request]

jobs:
  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      pull-requests: "read"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
