name: release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  GO_VERSION: "~1.18"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Test
        run: make test

  image_tag:
    name: Image tag
    outputs:
      image_tag: ${{ steps.tag.outputs.image_tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Output image tag
        id: tag
        run: |
          tag=$(echo "${GITHUB_REF}" | sed "s/^refs\/tags\/v//")
          if [ -z "$tag" ]; then
            exit 1
          fi
          echo "::set-output name=image_tag::$tag"

  docker:
    needs: [test, image_tag]
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write
    uses: ww24/linebot/.github/workflows/docker.yml@master
    with:
      image_tag: ${{ needs.image_tag.outputs.image_tag }}
      push: true
    secrets:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_PROJECT_NUMBER: ${{ secrets.GCP_PROJECT_NUMBER }}

  release:
    name: Release
    needs: [image_tag, docker]
    defaults:
      run:
        working-directory: terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.2
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Set image_tag
        run: |
          echo 'image_tag = "${{ needs.image_tag.outputs.image_tag }}"' \
            >> image_tag.auto.tfvars
      - name: Init
        run: terraform init
      - name: Validate
        run: terraform validate -no-color
      - name: Apply
        run: terraform apply -no-color
