name: test

on:
  workflow_call:
    inputs:
      golangci_lint_version:
        type: string
        required: false
        default: "v1.55.2"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: reviewdog/action-golangci-lint@v2.5.1
        with:
          go_version_file: go.mod
          github_token: ${{ secrets.github_token }}
          golangci_lint_flags: "--config=.golangci.yml"
          golangci_lint_version: ${{ inputs.golangci_lint_version }}
          reporter: github-check
          level: error
          fail_on_error: "false"

  test:
    name: Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: read
    env:
      FIRESTORE_EMULATOR_HOST: localhost:8833
    services:
      firestore:
        image: ghcr.io/${{ github.repository_owner }}/firestore-emulator:latest
        credentials:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        ports:
          - 8833:8833
        env:
          HOST_PORT: 0.0.0.0:8833
        options: >-
          --health-cmd "curl http://localhost:8833"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/cache@v3.3.3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v5.0.0
        with:
          go-version-file: go.mod
      - name: Test
        run: make test

  check_uncommitted:
    name: Check uncommitted changes
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-go@v5.0.0
        with:
          go-version-file: go.mod
      - name: Check generated files
        run: |
          make generate
          if [ -n "$(git status --porcelain)" ]; then
              echo "uncommitted changes"
              git status
              git --no-pager diff
              exit 1
          fi
